version: '3.7'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local

services:

  # General application container.
  # Could be run with many replica on demand.
  php:
    # Both php and CLI containers should use the same container.
    # image: os2subsites/os2subsites8:0.1.2
    build: .docker/os2subsites
    volumes:
      - ./.docker/logs:/var/log:delegated
      #- ./:/opt/drupal:delegated
      #- ./scripts/os2subsites_provision:/opt/drupal/scripts/os2subsites_provision
      #- ./.docker/os2subsites/os2subsite:/etc/sudoers.d/os2subsite
    depends_on:
      - db
    ports:
      - "${WEB_SERVER_PORT}:80"
    networks:
      - backend
      - frontend
    env_file:
      - .env_docker_compose

  db:
    image: mysql:5.7
    volumes:
      - ./.docker/mariadb/data:/var/lib/mysql:delegated
      #- ./.docker/mariadb/my.cnf:/etc/mysql/conf.d/10-default.cnf:ro,delegated
    env_file:
      - .env_docker_compose
    networks:
      - backend
