version: '3.7'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local

services:

  # General application container.
  # Could be run with many replica on demand.
  php:
    # Both php and CLI containers should use the same container.
    image: dkbellcom/os2subsites8:0.0.1
    volumes:
      - ./.docker/logs:/var/log:delegated
      - ./scripts/os2subsites_provision:/opt/drupal/scripts/os2subsites_provision
      - ./.docker/os2subsites/os2subsite:/etc/sudoers.d/os2subsite
    depends_on:
      - db
    ports:
      - "${WEB_SERVER_PORT}:80"
    networks:
      - backend
      - frontend
    environment:
      ## Environment sensitive settings. See .env file.
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DRUPAL_HASH_SALT=${DRUPAL_HASH_SALT}
      - BASEDIR=/opt/drupal
      - SERVERIP=127.0.0.1
      - PROFILE=minimal
      - EMAIL=drupal@bellcom.dk
      - SCRIPTDIR=/opt/drupal/scripts
      - DRUSH=/usr/local/bin/php drush
      - DBHOST=db
      - DBUSER_HOST=%
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASS=root
      - ADMINPASS=admin
      - VHOSTTEMPLATE=$SCRIPTDIR/../os2subsites_provision_config/vhost-template.txt
      - MULTISITE=$BASEDIR/web
      - SITESFILE=$MULTISITE/sites/sites.php
      - TMPDIRBASE=$BASEDIR/tmp
      - LOGDIRBASE=$BASEDIR/logs
      - SESSIONDIRBASE=$BASEDIR/sessions
      - SITEADMIN=subsiteadmin
      - APACHEUSER=www-data
      - USER=root

        # Version of Drupal core. Accepted values 7,8
      - DRUPAL=8

        # Additional option for site-install command
      - INSTALL_OPTIONS=""


  db:
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb/data:/var/lib/mysql:delegated
      - ./.docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro,delegated
    environment:
      ## Environment sensitive settings. See .env file.
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend
